### ISSUE TITLE
Mere question: How far along is Recombine?

### ISSUE THREAD

**Issue by gistya** [ReSwift/Recombine#1]
Mere question: How far along is Recombine?

At my work, we use ReSwift currently in a SwiftUI/Combine project. So this is a very appealing project to me. Would be interested to help with it, but I'm curious how far along in the development cycle you would say this is? Like, is it already production-ready or are there significant areas that still need polishing first?

Thanks!

**Comment by Qata** [comment]
It’s production ready. I’m using it at my work to build a safety critical app.

**Comment by Qata** [comment]
I just released version 1.0.0, which I’ll be introducing at my work shortly. It’s a combination of everything I learned while trying to scale up Recombine. Good luck with it, if you decide to use it!
