### ISSUE TITLE
Update diagram in the README's About Recombine section

### ISSUE THREAD

**Issue by nikitamounier** [ReSwift/Recombine#4]
I had some free time, so I thought I might try making an up-to-date and faithful diagram showing the flow of Recombine (since the one in the [About Recombine](https://github.com/ReSwift/Recombine#about-recombine) section is from ReactiveReSwift). I made two versions, let me know what you think :)

Here are the svg versions for the [first](https://vectr.com/prayfortech/crIYWZ7Rb.svg?width=800&height=800&select=crIYWZ7Rbpage0) and [second](https://vectr.com/prayfortech/f6OlwExjr.svg?width=800&height=800&select=f6OlwExjrpage0) one (GitHub comments don't support svg images, but they are supported on normal GitHub markdown with repo files).

![recombine](https://user-images.githubusercontent.com/36044205/108242252-fe219900-714c-11eb-9632-b4e19bc1b46b.png)
-----------------
![recombine-alt](https://user-images.githubusercontent.com/36044205/108242352-1db8c180-714d-11eb-84b5-22867ce66326.png)

**Comment by Qata** [comment]
Oh thank you so much! I was just gonna use Omnigraffle and modify the current one. I like the second one better! If you're okay with it, could you make a pull request to change it?

**Comment by nikitamounier** [comment]
Done!
