### ISSUE TITLE
Add a @StoreBinding property wrapper

### ISSUE THREAD

**Issue by nikitamounier** [ReSwift/Recombine#6]
Hi, I'd love to build upon the great progress already made with bindings in Recombine. In the last update, `binding(state:action:)` & friends were added to the `StoreProtocol` to easily create a binding with the store, which reads its state on `get` and dispatches an action on `set`. Side-by-side with vanilla SwiftUI bindings, it looks like this:

```swift
struct VanillaBindedView: View {
    @ObservedObject private var viewModel: ViewModel
    
    var body: some View {
        TextField("Search", text: $viewModel.searchText)
    }
}

struct RecombineBindedView: View {
    @EnvironmentObject private var store: SubStore<Redux.State.UserProfiles, Redux.Action.Refined.UserProfilesAction>
    
    private var searchTextBinding: Binding<String> {
        store.binding(state: \.searchText, actions: { .searchProfile($0) })
    }
    
    var body: some View {
        TextField("Search", text: searchTextBinding)
    }
}
```

While the vanilla version takes a simple dollar sign to create the binding, the Recombine version necessitates creating a custom binding in a computed property in an unnatural way. Indeed, rarely do we ever actually make contact with the `Binding` struct itself – it's usually through its property wrapper, or the `projectedValue` of other property wrappers like `@State`, `@ObservedObject`, `@StateObject`, or `@EnvironmentObject`. And because we create the `Binding` directly, we don't use the dollar sign which we've gotten used to meaning a binding in most cases. Creating bindings this way, while definitely much better than nothing, feels very un-SwiftUI-like.

Of course, one could just say that you could declare the binding inside the `TextField` initialiser itself – however, I am an advocate for keeping view logic outside the `body` declaration, and it wouldn't take away much from the clunkiness anyways.

One of my favourite parts of Recombine is the seamless transition one has when moving from vanilla MVVM-style SwiftUI. It moves all the architectural complexity out of the views into self-contained types like `State`, `Action`, or `Middleware`, and doesn't throw new views at you (I'm looking at you, `WithViewStore` and `ForEachStore`). So, at the view declaration, it all feels pretty natural – that is, until you create a binding.

So, I'd like to propose a solution to making bindings feel more natural and SwiftUI-like in Recombine: a new `@StoreBinding` property wrapper. Ultimately, it would look something like this:
```swift
struct RecombineBindedView: View {
    @EnvironmentObject private var store: SubStore<Redux.State.UserProfiles, Redux.Action.Refined.UserProfilesAction>
    @StoreBinding(state: \.searchText, refinedAction: { .searchProfile($0) }) var searchText
    
    var body: some View {
        TextField("Search", text: $searchText)
    }
}
```

I believe this would make a profound difference. First of all, the `state` and `refinedAction` "lenses" are now on the same level as the declaration, instead of being nested inside a computed property, which I believe improves readability. More importantly however, is the fact that this is a property wrapper, like `@Binding`, which presents a `projectedValue` of type `Binding`, like `@Binding` – you get the idea, it's very similar to `@Binding`.

Just to give myself an idea of how it could look, I made a quick implementation here:
```swift
@propertyWrapper 
public struct StoreBinding<Value, Store: StoreProtocol> {
    private var store: Store
    private var state: Value
    
    private let stateLens: (Store.SubState) -> Value
    private let actionStrata: ActionStrata<Store.RawAction, Store.SubRefinedAction>
    
    public var wrappedValue: Value { state }
    
    private init(store: Store, state stateLens: @escaping (Store.SubState) -> Value, action: ActionStrata<Store.RawAction, Store.SubRefinedAction>) {
        self.store = store
        self.state = stateLens(store.state)
        self.stateLens = stateLens
        self.actionStrata = action
    }
    
    // with raw action
    init(_ store: Store, state stateLens: @escaping (Store.SubState) -> Value, rawAction: (Value) -> Store.RawAction) {
        self.init(store: store, state: stateLens, action: .raw(rawAction(stateLens(store.state))))
    }
    
    // with refined action
    init(_ store: Store, state stateLens: @escaping (Store.SubState) -> Value, refinedAction: (Value) -> Store.SubRefinedAction) {
        self.init(store: store, state: stateLens, action: .refined(refinedAction(stateLens(store.state))))
    }

    public var projectedValue: Binding<Value> {
        switch actionStrata {
        case let .raw(rawAction):
            return Binding<Value>(get: { self.stateLens(store.state) }, set: { _ in self.store.dispatch(raw: rawAction)})
        case let .refined(refinedAction):
            return Binding<Value>(get: { self.stateLens(store.state) }, set: { _ in self.store.dispatch(refined: refinedAction) })
        }
    }
}
```

There's a couple things to note here. This implementation wouldn't actually work – here the `store` is passed into the initialiser, however properties are run before `self` is available, so in the view declaration, I wouldn't be able pass the `@EnvironmentObject`'s `store` into the property wrapper initialiser. In reality, I just wanted to make the `store` available to me so that I could play around with it.

Nonetheless, this does give a good idea of what implementing `@StoreBinding` would look like. Firstly, `wrappedValue` only has a getter reflecting its current value. Meanwhile, the `projectedValue` is what presents a binding, to reflect `@Binding`'s behaviour. 

I also think it's very important to give the ability to dispatch both raw and refined actions in the binding. Thankfully, your `ActionStrata` enum made that very easy – I hope it's a feature which will come to the current `binding(state:action:)` functions we have today. However, since we don't have that right now, I had to use the normal `Binding(get:set:)` initialiser in the `projectedValue`. Once we do, though, they'd be replaced by the `binding(state:action:)` functions.

Really the only difficulty with implementing `@StoreBinding` will be accessing the current store (passing it in in the view's initialiser would be sub-optimal in my opinion). I know that there's an experimental feature with property wrappers which lets you access the wrapper's enclosing/parent instance, which is used by the `@Published` property wrapper. Unfortunately, that wouldn't work because the enclosing instance has to be a class. You have way more experience than me though, so hopefully you'd find a solution!

I would love to hear your thoughts on this! I truly think this would be an important and meaningful feature to add to Recombine, elevating code clarity, readability, and ergonomics, especially for those who are used to vanilla SwiftUI. Comparing the two `RecombineBindedView`s, one using the current method, and the other using `@StoreBinding` – it's like night and day.

**Comment by Qata** [comment]
This might just work. I've been using Recombine in practice on a large project and have practically abandoned
usage of `@EnvironmentObject` after realising its limitations, and instead we're now treating the store as a global (which also makes previews a lot easier).

Sorry for taking so long to reply, I've been working on a novel 😅

**Comment by nikitamounier** [comment]
Interesting – does treating the store as a global impact performance? I know that thread-safety isn't an issue, since all state changes are made on the `Scheduler` passed into the store initialiser.

**Comment by Qata** [comment]
I haven't tested performance but I'd imagine, since it's even less overhead than using `EnvironmentObject`, there'd be gains (albeit small).

**Comment by Qata** [comment]
Added in 2.0.0!
